[package]
name = "autoswap-rust-sdk"
license = "MIT"
authors = [""]
description = "AutoSwappr library in Rust"
repository = "https://github.com/BlockheaderWeb3-Community/autoswap-rust-sdk"
keywords = [
    "starknet",
    "cairo",
    "defi",
    "swap",
    "ekubo",
    "autoswappr",
    "swap"
]
documentation = ""
exclude = [".github/**"]
version = "0.1.0"
edition = "2024"

[dependencies]
starknet = "0.17.0"
thiserror = "2.0.16"
serde = {version="1.0.219", features=["derive"]}